services:
  - type: web
    name: secretaria-ia-final
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        value: https://secretaria-ia-final.onrender.com
      - key: PORT
        value: 3000
